# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = false

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx
subs = [
    "https://raw.githubusercontent.com/ReaJason/Clash-Butler/master/clash.yaml",
    "https://raw.githubusercontent.com/shaoyouvip/free/refs/heads/main/all.yaml",
    "https://raw.githubusercontent.com/ccpthisbigdog/freedomchina/refs/heads/main/clab.yaml",
    "https://raw.githubusercontent.com/ermaozi/get_subscribe/refs/heads/main/subscribe/clash.yml",
    "https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/clash.yml",
    "https://raw.githubusercontent.com/mai19950/clash_config/refs/heads/main/sub/clash.yaml",
    "https://www.xrayvip.com/free.yaml",
    "https://raw.githubusercontent.com/ts-sf/fly/main/clash",
    "https://raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml",
    "https://bpanel.hurricane-tx.workers.dev/86c50e3a-5b87-49dd-1234-03c7f2735e40/cl",
    "https://8jgpUP.mcsslk.xyz/4261409d9bf605f7cbfc6df1b95745d2",
    "https://GrK8wi.tosslk.xyz/366f2f5b2a75b0205696a3be05e3316e"
]

# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = true
rename_pattern = "${COUNTRYCODE}_${CITY}_${ISP}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = true
# 代理节点池
pools = [
    "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml",
    "https://raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml",
    "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt",
]

# 测试分组大小
test_group_size = 50

# 连通性测试
[connect_test]
url = "http://www.google.com/generate_204"
expected = 204
timeout = 1000

# 带宽测速配置
[speed_test]
enabled = false
url = "https://speed.cloudflare.com/__down?bytes=104857600"
timeout = 3000
