# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = false

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx
subs = [
    "https://www.xrayvip.com/free.yaml",
    "https://raw.githubusercontent.com/ts-sf/fly/main/clash",
    "https://raw.githubusercontent.com/ReaJason/Clash-Butler/master/clash.yaml",
    "https://raw.githubusercontent.com/shaoyouvip/free/refs/heads/main/all.yaml",
    "https://raw.githubusercontent.com/ccpthisbigdog/freedomchina/refs/heads/main/clab.yaml",
    "https://raw.githubusercontent.com/ermaozi/get_subscribe/refs/heads/main/subscribe/clash.yml",
    "https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/clash.yml",
    "https://raw.githubusercontent.com/mai19950/clash_config/refs/heads/main/sub/clash.yaml",
    "https://raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml",
    "https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml",
    "https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml",
    "https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta-2.yaml",
    "http://141.147.161.50:12580/clash/proxies",
    "http://155.248.172.106:12580/clash/proxies",
    "http://66.42.50.118:12580/clash/proxies",
    "https://clashe.eu.org/clash/proxies",
    "https://proxy.crazygeeky.com/clash/proxies",
    "https://proxypool.link/clash/proxies",
    "https://proxypool1999.banyunxiaoxi.icu/clash/proxies",
    "https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml",
    "https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml",
    "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml",
    "https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_yaml.yml",
    "https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/Clash.yaml",
    "https://raw.githubusercontent.com/PangTouY00/Auto_proxy/main/Long_term_subscription_num",
    "https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml",
    "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml",
    "https://raw.githubusercontent.com/Vauth/node/main/Main",
    "https://raw.githubusercontent.com/lagzian/SS-Collector/main/mix_clash.yaml",
    "https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/sub.txt",
    "https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/all.yaml",
    "https://raw.githubusercontent.com/Misaka-blog/chromego_merge/main/sub/merged_proxies_new.yaml",
    "https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/yudou66.yaml",
    "https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/blues.yaml",
    "https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/clashmeta.yaml",
    "https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/ndnode.yaml",
    "https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/nodev2ray.yaml",
    "https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/nodefree.yaml",
    "https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/v2rayshare.yaml",
    "https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/wenode.yaml",
    "https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash",
    "https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub",
    "https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml",
    "https://8jgpUP.mcsslk.xyz/4261409d9bf605f7cbfc6df1b95745d2",
    "https://GrK8wi.tosslk.xyz/366f2f5b2a75b0205696a3be05e3316e"
]

# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = true
rename_pattern = "${COUNTRYCODE}_${CITY}_${ISP}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = true
# 代理节点池
pools = [
    "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml",
    "https://raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml",
    "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt",
]

# 测试分组大小
test_group_size = 50

# 连通性测试
[connect_test]
url = "http://www.google.com/generate_204"
expected = 204
timeout = 1000

# 带宽测速配置
[speed_test]
enabled = false
url = "https://speed.cloudflare.com/__down?bytes=104857600"
timeout = 3000
